import Link from "next/link";
import HeroPortrait from "@/components/landing/HeroPortrait";
import ServiceTicker from "@/components/landing/ServiceTicker";
import StatsBand from "@/components/landing/StatsBand";
import HowItWorks from "@/components/landing/HowItWorks";
import DifferenceSplit from "@/components/landing/DifferenceSplit";
import FeatureBento from "@/components/landing/FeatureBento";
import PricingTeaser from "@/components/landing/PricingTeaser";
import CtaBand from "@/components/landing/CtaBand";
import JsonLd from "@/components/seo/JsonLd";
import Faq from "@/components/site/Faq";
import SiteFooter from "@/components/site/SiteFooter";
import SiteNav from "@/components/site/SiteNav";
import { faqSchema, type FaqItem } from "@/lib/seo/jsonld";

/**
 * Answers are written from what the product actually does — real SIMs,
 * 20-minute sessions, pay-per-SMS, automatic refund. FAQPage schema is only
 * legitimate if the same text is visible on the page, so these feed both the
 * accordion and the structured data below.
 */
const HOME_FAQ: FaqItem[] = [
  {
    question: "What is a non-VoIP phone number?",
    answer:
      "A non-VoIP number is one issued to a physical SIM card on a mobile network, rather than one generated by an internet calling service. Apps can tell the difference: every number range is registered to a carrier, and lookup databases flag ranges that belong to VoIP providers. Our numbers come from real SIM cards in real devices, so they read as ordinary mobile numbers.",
  },
  {
    question: "Why do Telegram, Tinder and Google block VoIP numbers?",
    answer:
      "Because VoIP numbers are cheap and effectively unlimited, which makes them the tool of choice for bulk fake-account creation. Blocking VoIP ranges is the simplest way for a platform to raise the cost of spam. A real SIM number is tied to a physical line and a carrier, so it passes the check that rejects VoIP.",
  },
  {
    question: "How long does my temporary number last?",
    answer:
      "Each number stays active for 20 minutes from the moment it is assigned. That is enough time to request a code and receive it — most arrive within seconds. If you need a number for longer, for an account you will sign into repeatedly, we also offer long-term rentals from the dashboard.",
  },
  {
    question: "What happens if I don't receive an SMS?",
    answer:
      "You are not charged. You only pay when a code is actually delivered. If the 20-minute window expires without an SMS, the amount is refunded to your wallet automatically — you do not need to contact support or open a ticket. You can also cancel before the code arrives and your balance is restored immediately.",
  },
  {
    question: "Can I reuse a number?",
    answer:
      "Not with a pay-per-SMS order. Each one gives you a number for a single verification, and once the session ends the number returns to the pool and may be reassigned. If you need the same number to stay yours — to receive repeated login codes, for example — use a long-term rental instead, which holds the number for the period you choose.",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteNav />

      <JsonLd data={faqSchema(HOME_FAQ)} />

      {/* ─── Hero ─── */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-20 md:pt-24 md:pb-24">
        <div className="grid lg:grid-cols-[1.1fr_1fr] gap-14 lg:gap-20 items-center">
          {/* Left — claim */}
          <div className="max-w-xl">
            <div className="inline-flex items-center gap-2 mb-8 px-3 py-1 rounded-full border-terracotta/25 bg-terracotta/5">
              <span className="w-1.5 h-1.5 rounded-full bg-terracotta" />
              <span className="font-mono text-xs text-terracotta">
                Real SIM cards&nbsp;&bull;&nbsp;Not VoIP
              </span>
            </div>

            <h1 className="font-sans text-5xl sm:text-6xl md:text-7xl font-extrabold leading-[1.02] tracking-tight mb-6">
              Verify anything.
              <br />
              <span className="text-accent">Instantly.</span>
            </h1>

            {/* Keyword-bearing subheading: the H1 is a brand tagline, so this
                is where the page states what it actually is, in the words
                people search for. */}
            <p className="text-muted text-base sm:text-lg max-w-md mb-4">
              <strong className="text-foreground font-semibold">
                Temporary phone numbers for SMS verification.
              </strong>{" "}
              Receive verification codes online from real SIM cards — not
              VoIP — across 1,300+ services and 150+ countries.
            </p>
            <p className="text-muted text-sm max-w-md mb-10">
              Pay only when a code arrives. Automatic refund if it doesn&apos;t.
              No subscription.
            </p>

            <div className="flex flex-wrap items-center gap-4 mb-12">
              <Link
                href="/auth"
                className="inline-flex items-center min-h-11 px-6 bg-pine text-paper font-semibold rounded-full hover:bg-pine-deep transition-colors text-sm"
              >
                Get a number&nbsp;&rarr;
              </Link>
              <a
                href="#pricing"
                className="inline-flex items-center justify-center min-h-11 px-6 border border-line-strong text-foreground rounded-full hover:border-muted transition-colors text-sm"
              >
                See pricing
              </a>
            </div>

            <div className="flex items-center gap-3">
              <div className="flex -space-x-2">
                {["A", "K", "R", "M"].map((letter) => (
                  <span
                    key={letter}
                    className="w-7 h-7 rounded-full flex items-center justify-center text-[10px] font-bold text-muted ring-2 ring-background bg-line border border-surface"
                  >
                    {letter}
                  </span>
                ))}
              </div>
              <span className="text-xs text-muted">
                Trusted by 2,400+ developers
              </span>
            </div>
          </div>

          {/* Right — portrait + floating bubbles */}
          <HeroPortrait />
        </div>
      </section>

      {/* ─── Service ticker ─── */}
      <ServiceTicker />

      <div className="pt-24">
        <StatsBand />
        <HowItWorks />
        <DifferenceSplit />
        <FeatureBento />
        <PricingTeaser />
        <Faq items={HOME_FAQ} />
        <CtaBand />
      </div>

      <SiteFooter />
    </div>
  );
}
